[programs.localnet]
anchor_escrow = "14dVNNagfEYzDtRTA4Bwav7s5RLrrrrdNUv6zB7p5Wpn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "https://rpc-mainnet-fork.dappio.xyz"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
